# The site is served by GitHub Pages (chronic-trading.github.io/trading-lab)
# and license validation runs as a Supabase Edge Function (validate-whop).
# Nothing is deployed on Netlify anymore — skip every build so pushes stop
# consuming build credits. Safe to delete the Netlify site from the dashboard.
[build]
  ignore = "exit 0"
