import { useState } from 'react'
import { X, Copy, Check, FileText } from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'
import type { Build } from '../types'
import { getConceptById, getSynergiesFor } from '../data/concepts'

interface Props {
  build: Build
  open: boolean
  onClose: () => void
}

function buildExportText(build: Build): string {
  const concepts = build.conceptIds.map(id => getConceptById(id)).filter(Boolean)
  const synergies = getSynergiesFor(build.conceptIds)

  const divider = '─'.repeat(52)
  const lines: string[] = [
    `TRADING BUILD: ${build.name}`,
    `Instrument : ${build.instrument}`,
    `Date       : ${new Date(build.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
    `Concepts   : ${concepts.length}`,
    `Synergies  : ${synergies.length}`,
    '',
    divider,
    'CONCEPTS',
    divider,
    '',
  ]

  concepts.forEach((c, i) => {
    if (!c) return
    lines.push(`${i + 1}. ${c.name}`)
    lines.push(`   Tier     : ${c.tier.charAt(0).toUpperCase() + c.tier.slice(1)}`)
    lines.push(`   Category : ${c.category.charAt(0).toUpperCase() + c.category.slice(1)}`)
    lines.push(`   About    : ${c.description}`)
    lines.push(`   Use it   : ${c.howToUse}`)
    lines.push('')
  })

  if (synergies.length > 0) {
    lines.push(divider)
    lines.push('SYNERGIES')
    lines.push(divider)
    lines.push('')
    synergies.forEach(s => {
      const a = getConceptById(s.conceptA)
      const b = getConceptById(s.conceptB)
      if (!a || !b) return
      const stars = '★'.repeat(s.strength) + '☆'.repeat(3 - s.strength)
      lines.push(`${stars}  ${a.name}  ↔  ${b.name}`)
      lines.push(`      ${s.notes[0] ?? ''}`)
      lines.push('')
    })
  }

  if (build.notes) {
    lines.push(divider)
    lines.push('NOTES')
    lines.push(divider)
    lines.push('')
    lines.push(build.notes)
    lines.push('')
  }

  lines.push(divider)
  lines.push('Generated by Trading Lab')

  return lines.join('\n')
}

export function ExportBuildModal({ build, open, onClose }: Props) {
  const [copied, setCopied] = useState(false)
  const text = buildExportText(build)

  const copy = async () => {
    await navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm"
          onClick={onClose}
        >
          <motion.div
            initial={{ scale: 0.95, opacity: 0, y: 8 }}
            animate={{ scale: 1, opacity: 1, y: 0 }}
            exit={{ scale: 0.95, opacity: 0, y: 8 }}
            transition={{ duration: 0.18 }}
            className="w-full max-w-2xl bg-[#0c0c15] border border-slate-700/60 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[85vh]"
            onClick={e => e.stopPropagation()}
          >
            {/* Header */}
            <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800/60 flex-shrink-0">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-xl bg-blue-500/10 border border-blue-500/25 flex items-center justify-center">
                  <FileText size={14} className="text-blue-400" />
                </div>
                <div>
                  <p className="text-[14px] font-bold text-white">Export Build</p>
                  <p className="text-[11px] text-slate-500 mt-0.5">{build.name}</p>
                </div>
              </div>
              <button
                onClick={onClose}
                className="w-8 h-8 flex items-center justify-center rounded-xl text-slate-500 hover:text-slate-200 hover:bg-slate-800 transition-all"
              >
                <X size={15} />
              </button>
            </div>

            {/* Text preview */}
            <div className="flex-1 overflow-y-auto p-4">
              <pre
                className="text-[12px] text-slate-300 leading-relaxed whitespace-pre-wrap bg-slate-900/60 border border-slate-800/60 rounded-2xl p-4 font-mono"
                style={{ fontFamily: "'JetBrains Mono', monospace" }}
              >
                {text}
              </pre>
            </div>

            {/* Footer */}
            <div className="flex items-center justify-end gap-2.5 px-6 py-4 border-t border-slate-800/60 flex-shrink-0">
              <button
                onClick={onClose}
                className="px-4 py-2 rounded-xl text-[12px] font-semibold text-slate-400 hover:text-slate-200 hover:bg-slate-800 transition-all"
              >
                Close
              </button>
              <button
                onClick={copy}
                className={`flex items-center gap-2 px-5 py-2 rounded-xl text-[12px] font-bold border transition-all
                  ${copied
                    ? 'bg-emerald-500/15 border-emerald-500/40 text-emerald-300'
                    : 'bg-blue-500/15 border-blue-500/35 text-blue-300 hover:bg-blue-500/25 hover:border-blue-400/50'}`}
              >
                {copied ? <Check size={13} /> : <Copy size={13} />}
                {copied ? 'Copied!' : 'Copy to clipboard'}
              </button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  )
}
